class script(object):
    # Plain text with names and URLs
    NEON_TXT = [
    "📌 Absolute Duo - https://t.me/NeonFilesBot?start=Z2V0LTg0MjA4OTc5MDAwMjQ0LTk3MjQxMzIwOTg4Mzc3",
    "📌 A Returner's Magic be Special",
    "📌 Akashic Records of Magical",
    "📌 Alya Sometimes hides her",
    "📌 An Archdemons Dilemma",
    "📌 Aristocrats Otherworldly Advent",
    "📌 Armed Girl's Machiavellism",
    "📌 Aesthetica of a Rogue Hero",
    "📌 Attack On Titan",
    "📌 Attack On Titan Season 02",
    "📌 Attack On Titan Season 03",
    "📌 Attack On Titan Season 04",
    "📌 Battle Game In 5 Seconds",
    "📌 Beast Tamer",
    "📌 Berserk of Gluttony",
    "📌 Black Summoner",
    "📌 Blue Lock",
    "📌 Blue Lock S2",
    "📌 BOFURI: I Don't get Hurt S01",
    "📌 BOFURI: I Don't get Hurt S02",
    "📌 Buddy Complex",
    "📌 Buddy Complex Specials",
    "📌 Buddy Daddies",
    "📌 Campfire Cooking in Another",
    "📌 Cautious Hero",
    "📌 ChainSaw Man",
    "📌 Chained Soldier",
    "📌 Chaika Avenging Battle",
    "📌 Chaika Coffin Princess",
    "📌 Chivalry Of a Failed Knight",
    "📌 Code:Breaker",
    "📌 Combatants Will Be Dispatched!",
    "📌 Dandadan",
    "📌 Darling in the Franxx",
    "📌 Dawn of The Witch",
    "📌 Death March to the Parallel Wld",
    "📌 Dead Mount DeathPlay",
    "📌 Demon King Daimao",
    "📌 Demon King Daimao Specials",
    "📌 Demon Slayer S1",
    "📌 Demon Slayer Movie 01",
    "📌 Demon Slayer S2 Part 01",
    "📌 Demon Slayer S2 Part 02",
    "📌 Demon Slayer S3",
    "📌 Demon Slayer S4",
    "📌 Demon Sword Master of Excalibur",
    "📌 Failure Frame",
    "📌 Farming Life in another World",
    "📌 Goblin Slayer S01",
    "📌 Goblin Slayer S02",
    "📌 Goblin Slayer: G.Crown (Movie)",
    "📌 Gods' Games we Play",
    "📌 Hell's Paradise",
    "📌 How a Realist Hero Rebuilt",
    "📌 How a Realist Hero Rebuilt S2",
    "📌 How not to Summon a Demon",
    "📌 Hundred",
    "📌 I Got a Cheat Skill in Another",
    "📌 I Parry Everything",
    "📌 I Shall survive using potions",
    "📌 I've been killing Slimes for 300",
    "📌 I'm Quitting Heroing",
    "📌 In another world with my S01",
    "📌 In another world with my S02",
    "📌 Infinite Dendrogram",
    "📌 Isekai Cheat Magician",
    "📌 Jujutsu Kaisen",
    "📌 Kaiju No 8",
    "📌 Knight's & Magic",
    "📌 Konosuba! An Explosion",
    "📌 Konosuba Movie",
    "📌 Konosuba Season 01",
    "📌 Konosuba Season 02",
    "📌 Konosuba Season 03",
    "📌 Log Horizon",
    "📌 Log Horizon Season 02",
    "📌 Log Horizon Season 03",
    "📌 Lookism",
    "📌 Mashle: Magic And Muscles",
    "📌 Mashle: Magic And Muscles S02",
    "📌 My Dress-Up Darling",
    "📌 My Isekai life",
    "📌 My Instant Death Ability",
    "📌 Myriad Colors Phantom World",
    "📌 Myriad Colors Phantom Specials",
    "📌 My Unique Skill Makes Me OP",
    "📌 Ningen Fushin",
    "📌 Noblesse",
    "📌 One Punch Man",
    "📌 One Punch Man S2",
    "📌 Overflow Uncensored",
    "📌 OverLord",
    "📌 Our Last Crusade",
    "📌 Parallel World Pharmacy",
    "📌 Rage Of Bahamut",
    "📌 Re Monster",
    "📌 Record of Grancrest War",
    "📌 Re Reborn as a Vending Machine",
    "📌 Redo of Healer",
    "📌 Reincarnated as a Sword",
    "📌 Reincarnated as Slime S01",
    "📌 Reincarnated as Slime S02",
    "📌 Reincarnated as Slime S03",
    "📌 Reincarnated as Slime Movie",
    "📌 Reincarnatn of Strongest Exorcist",
    "📌 Rent-A-Girlfriend",
    "📌 Rent-A-Girlfriend Season 02",
    "📌 Rent-A-Girlfriend Season 03",
    "📌 Restaurant to Another World S1",
    "📌 Restaurant To Another World S2",
    "📌 Rokka",
    "📌 Shangri-La Frontier",
    "📌 Seirei Gensouki Spirit Chronicles",
    "📌 Skeleton Knight in another World",
    "📌 Sky Wizards Academy",
    "📌 Solo Leveling",
    "📌 Spy X Family",
    "📌 Spy X Family Season 02",
    "📌 Spy X Family : Code White",
    "📌 Suppose a Kid from the Last",
    "📌 Sword Art Online S1",
    "📌 Sword Art Online S2",
    "📌 Sword Art Online S3",
    "📌 Sword Art Online S4",
    "📌 Sword Art Online: Gun Gale",
    "📌 Sword Art Online Movies",
    "📌 Sweet Reincarnation",
    "📌 The Daily Life of the Immortal S1",
    "📌 The Daily Life of the Immortal S2",
    "📌 The Daily Life of the Immortal S3",
    "📌 The Daily Life of the Immortal S4",
    "📌 The Dreaming Boy is a Realist",
    "📌 The Eminence in Shadow S1",
    "📌 The Eminence in Shadow S2",
    "📌 The Executioner and Her Way of",
    "📌 The Foolish Angel Dances with",
    "📌 The God of HighSchool",
    "📌 The Greatest Alchemist",
    "📌 The Greatest Demon lord Reborn",
    "📌 The Hidden dungeon only I",
    "📌 The IceBlade Sorcerer",
    "📌 The Misfit of Demon King",
    "📌 The Misfit of Demon King S02",
    "📌 The Ossan Newbie Adventurer",
    "📌 The Rising of the Shield Hero S1",
    "📌 The Rising of the Shield Hero S2",
    "📌 The Rising of the Shield Hero S3",
    "📌 The Slime Diaries",
    "📌 The Strongest Sage with weakst",
    "📌 The Testament of Sister",
    "📌 The Testament of Sister S02",
    "📌 The Testament of Sister Special",
    "📌 The Weakest Tamer Began",
    "📌 Tomo-Chan is a Girl!",
    "📌 Toradora!",
    "📌 Toradora! Specials",
    "📌 Tower Of God",
    "📌 Tower Of God Season 02",
    "📌 Transformers Prime S1",
    "📌 Transformers Prime S2",
    "📌 Transformers Prime S3",
    "📌 Transformers Prime Movie",
    "📌 TsukiMichi Moonlit Fantasy S1",
    "📌 TsukiMichi Moonlit Fantasy S2",
    "📌 UQ Holder!",
    "📌 Unwanted undead Adventurer",
    "📌 Vermeil in Gold",
    "📌 Violet Evergarden",
    "📌 Wind Breaker",
    "📌 Wistoria : wand and sword",
    "📌 Wrong way to use Healing Magic"
    ]
    
