class script(object):
    # Plain text with names and URLs
    NEON_TXT = [
    "📌 Absolute Duo - https://t.me/NeonFilesBot?start=Z2V0LTI0NzUxNDI0ODk5MDAwMjktMjQ3MzEzNzUxNDIwOTU0Nw",
    "📌 A Returner's Magic be Special - https://t.me/NeonFilesBot?start=Z2V0LTg0MjA4OTc5MDAwMjQ0LTk3MjQxMzIwOTg4Mzc3",
    "📌 Akashic Records of Magical - https://t.me/NeonFilesBot?start=Z2V0LTEwMDI0ODc4NDUyNDEwMC0xMTMyODExMjY1MTIyMzM",
    "📌 Alya Sometimes hides her - https://t.me/NeonFilesBot?start=Z2V0LTExNDI4MzYxNDM1NzQ3NC0xMjczMTU5NTYzNDU2MDc",
    "📌 An Archdemons Dilemma - https://t.me/NeonFilesBot?start=Z2V0LTExMDQ3NDE2MDU0NTU1ODItMTExNzc3Mzk0NzQ0MzcxNQ",
    "📌 Aristocrats Otherworldly Advent - https://t.me/NeonFilesBot?start=Z2V0LTc4NDk0Nzk4MjgyMzcwMy03OTc5ODAzMjQ4MTE4MzY",
    "📌 Armed Girl's Machiavellism - https://t.me/NeonFilesBot?start=Z2V0LTE5ODY5MzA5MDkyNjc2NjItMjAwMDk2NTczOTEwMTAzNg",
    "📌 Aesthetica of a Rogue Hero - https://t.me/NeonFilesBot?start=Z2V0LTIxOTM0NDM0MDUzODczMDgtMjIwNjQ3NTc0NzM3NTQ0MQ",
    "📌 Attack On Titan - https://t.me/NeonFilesBot?start=Z2V0LTI4NDAwNDgwNjU1Njc3NTMtMjg2NzExNTIzNzM4OTI2MA",
    "📌 Attack On Titan Season 02 - https://t.me/NeonFilesBot?start=Z2V0LTI4NjgxMTc3MjUyMzQ1MDEtMjg4MjE1MjU1NTA2Nzg3NQ",
    "📌 Attack On Titan Season 03 - https://t.me/NeonFilesBot?start=Z2V0LTI4ODMxNTUwNDI5MTMxMTYtMjkwNzIxNDc1MTE5ODkwMA",
    "📌 Attack On Titan Season 04 - https://t.me/NeonFilesBot?start=Z2V0LTI5MDgyMTcyMzkwNDQxNDEtMjkzNzI4OTM4NjU1NjEzMA",
    "📌 Battle Game In 5 Seconds - https://t.me/NeonFilesBot?start=Z2V0LTIxMTgyNTY4MTY5OTQyMzMtMjEzMzI5NDEzNDY3Mjg0OA",
    "📌 Beast Tamer",
    "📌 Berserk of Gluttony",
    "📌 Black Summoner",
    "📌 Blue Lock",
    "📌 Blue Lock S2",
    "📌 BOFURI: I Don't get Hurt S01",
    "📌 BOFURI: I Don't get Hurt S02",
    "📌 Buddy Complex",
    "📌 Buddy Complex Specials",
    "📌 Buddy Daddies",
    "📌 Campfire Cooking in Another - https://t.me/NeonFilesBot?start=Z2V0LTMyOTgxODUwMTA4NDI4OS0zNDI4NTA4NDMwNzI0MjI",
    "📌 Cautious Hero - https://t.me/NeonFilesBot?start=Z2V0LTM0NDk1NjA2NzU0NzQyODEtMzQ2MzU5NTUwNTMwNzY1NQ",
    "📌 ChainSaw Man - https://t.me/NeonFilesBot?start=Z2V0LTQzMjA3MjI2MTI5ODg3MS00NDUxMDQ2MDMyODcwMDQ",
    "📌 Chained Soldier - https://t.me/NeonFilesBot?start=Z2V0LTMxNTU4MzE3MzY4MTg2NjgtMzE2OTg2NjU2NjY1MjA0Mg",
    "📌 Chaika Avenging Battle - https://t.me/NeonFilesBot?start=Z2V0LTI0NDAwNTU0MTUzMTY1OTQtMjQ1MjA4NTI2OTQ1OTQ4Ng",
    "📌 Chaika Coffin Princess - https://t.me/NeonFilesBot?start=Z2V0LTI0MjQwMTU2MDk3OTI3MzgtMjQzNzA0Nzk1MTc4MDg3MQ",
    "📌 Chivalry Of a Failed Knight - https://t.me/NeonFilesBot?start=Z2V0LTgzMDA1OTkzNTg1OTU0OC04NDMwOTIyNzc4NDc2ODE",
    "📌 Code:Breaker - https://t.me/NeonFilesBot?start=Z2V0LTMyMTY5ODM0OTUzNzgzNjktMzIzMjAyMDgxMzA1Njk4NA",
    "📌 Combatants Will Be Dispatched! - https://t.me/NeonFilesBot?start=Z2V0LTIxNzg0MDYwODc3MDg2OTMtMjE5MTQzODQyOTY5NjgyNg",
    "📌 Dandadan",
    "📌 Darling in the Franxx",
    "📌 Dawn of The Witch",
    "📌 Death March to the Parallel Wld",
    "📌 Dead Mount DeathPlay",
    "📌 Demon King Daimao",
    "📌 Demon King Daimao Specials",
    "📌 Demon Slayer S1",
    "📌 Demon Slayer Movie 01",
    "📌 Demon Slayer S2 Part 01",
    "📌 Demon Slayer S2 Part 02",
    "📌 Demon Slayer S3",
    "📌 Demon Slayer S4",
    "📌 Demon Sword Master of Excalibur",
    "📌 Failure Frame",
    "📌 Farming Life in another World",
    "📌 Goblin Slayer S01",
    "📌 Goblin Slayer S02",
    "📌 Goblin Slayer: G.Crown (Movie)",
    "📌 Gods' Games we Play",
    "📌 Hell's Paradise",
    "📌 How a Realist Hero Rebuilt",
    "📌 How a Realist Hero Rebuilt S2",
    "📌 How not to Summon a Demon",
    "📌 Hundred",
    "📌 I Got a Cheat Skill in Another",
    "📌 I Parry Everything",
    "📌 I Shall survive using potions",
    "📌 I've been killing Slimes for 300",
    "📌 I'm Quitting Heroing",
    "📌 In another world with my S01",
    "📌 In another world with my S02",
    "📌 Infinite Dendrogram",
    "📌 Isekai Cheat Magician",
    "📌 Jujutsu Kaisen",
    "📌 Kaiju No 8",
    "📌 Knight's & Magic",
    "📌 Konosuba! An Explosion",
    "📌 Konosuba Movie",
    "📌 Konosuba Season 01",
    "📌 Konosuba Season 02",
    "📌 Konosuba Season 03",
    "📌 Log Horizon",
    "📌 Log Horizon Season 02",
    "📌 Log Horizon Season 03",
    "📌 Lookism",
    "📌 Mashle: Magic And Muscles",
    "📌 Mashle: Magic And Muscles S02",
    "📌 My Dress-Up Darling",
    "📌 My Isekai life",
    "📌 My Instant Death Ability",
    "📌 Myriad Colors Phantom World",
    "📌 Myriad Colors Phantom Specials",
    "📌 My Unique Skill Makes Me OP",
    "📌 Ningen Fushin",
    "📌 Noblesse",
    "📌 One Punch Man",
    "📌 One Punch Man S2",
    "📌 Overflow Uncensored",
    "📌 OverLord",
    "📌 Our Last Crusade",
    "📌 Parallel World Pharmacy",
    "📌 Rage Of Bahamut",
    "📌 Re Monster",
    "📌 Record of Grancrest War",
    "📌 Re Reborn as a Vending Machine",
    "📌 Redo of Healer",
    "📌 Reincarnated as a Sword",
    "📌 Reincarnated as Slime S01",
    "📌 Reincarnated as Slime S02",
    "📌 Reincarnated as Slime S03",
    "📌 Reincarnated as Slime Movie",
    "📌 Reincarnatn of Strongest Exorcist",
    "📌 Rent-A-Girlfriend",
    "📌 Rent-A-Girlfriend Season 02",
    "📌 Rent-A-Girlfriend Season 03",
    "📌 Restaurant to Another World S1",
    "📌 Restaurant To Another World S2",
    "📌 Rokka",
    "📌 Shangri-La Frontier",
    "📌 Seirei Gensouki Spirit Chronicles",
    "📌 Skeleton Knight in another World",
    "📌 Sky Wizards Academy",
    "📌 Solo Leveling",
    "📌 Spy X Family",
    "📌 Spy X Family Season 02",
    "📌 Spy X Family : Code White",
    "📌 Suppose a Kid from the Last",
    "📌 Sword Art Online S1",
    "📌 Sword Art Online S2",
    "📌 Sword Art Online S3",
    "📌 Sword Art Online S4",
    "📌 Sword Art Online: Gun Gale",
    "📌 Sword Art Online Movies",
    "📌 Sweet Reincarnation",
    "📌 The Daily Life of the Immortal S1",
    "📌 The Daily Life of the Immortal S2",
    "📌 The Daily Life of the Immortal S3",
    "📌 The Daily Life of the Immortal S4",
    "📌 The Dreaming Boy is a Realist",
    "📌 The Eminence in Shadow S1",
    "📌 The Eminence in Shadow S2",
    "📌 The Executioner and Her Way of",
    "📌 The Foolish Angel Dances with",
    "📌 The God of HighSchool",
    "📌 The Greatest Alchemist",
    "📌 The Greatest Demon lord Reborn",
    "📌 The Hidden dungeon only I",
    "📌 The IceBlade Sorcerer",
    "📌 The Misfit of Demon King",
    "📌 The Misfit of Demon King S02",
    "📌 The Ossan Newbie Adventurer",
    "📌 The Rising of the Shield Hero S1",
    "📌 The Rising of the Shield Hero S2",
    "📌 The Rising of the Shield Hero S3",
    "📌 The Slime Diaries",
    "📌 The Strongest Sage with weakst",
    "📌 The Testament of Sister",
    "📌 The Testament of Sister S02",
    "📌 The Testament of Sister Special",
    "📌 The Weakest Tamer Began",
    "📌 Tomo-Chan is a Girl!",
    "📌 Toradora!",
    "📌 Toradora! Specials",
    "📌 Tower Of God",
    "📌 Tower Of God Season 02",
    "📌 Transformers Prime S1",
    "📌 Transformers Prime S2",
    "📌 Transformers Prime S3",
    "📌 Transformers Prime Movie",
    "📌 TsukiMichi Moonlit Fantasy S1",
    "📌 TsukiMichi Moonlit Fantasy S2",
    "📌 UQ Holder!",
    "📌 Unwanted undead Adventurer",
    "📌 Vermeil in Gold",
    "📌 Violet Evergarden",
    "📌 Wind Breaker",
    "📌 Wistoria : wand and sword",
    "📌 Wrong way to use Healing Magic"
    ]
    
