class script(object):
    # Plain text with names and URLs
    NEON_TXT = [
    "📌 Absolute Duo - https://t.me/NeonFilesBot?start=Z2V0LTI0NzUxNDI0ODk5MDAwMjktMjQ3MzEzNzUxNDIwOTU0Nw",
    "📌 A Returner's Magic be Special - https://t.me/NeonFilesBot?start=Z2V0LTg0MjA4OTc5MDAwMjQ0LTk3MjQxMzIwOTg4Mzc3",
    "📌 Akashic Records of Magical - https://t.me/NeonFilesBot?start=Z2V0LTEwMDI0ODc4NDUyNDEwMC0xMTMyODExMjY1MTIyMzM",
    "📌 Alya Sometimes hides her - https://t.me/NeonFilesBot?start=Z2V0LTExNDI4MzYxNDM1NzQ3NC0xMjczMTU5NTYzNDU2MDc",
    "📌 An Archdemons Dilemma - https://t.me/NeonFilesBot?start=Z2V0LTExMDQ3NDE2MDU0NTU1ODItMTExNzc3Mzk0NzQ0MzcxNQ",
    "📌 Aristocrats Otherworldly Advent - https://t.me/NeonFilesBot?start=Z2V0LTc4NDk0Nzk4MjgyMzcwMy03OTc5ODAzMjQ4MTE4MzY",
    "📌 Armed Girl's Machiavellism - https://t.me/NeonFilesBot?start=Z2V0LTE5ODY5MzA5MDkyNjc2NjItMjAwMDk2NTczOTEwMTAzNg",
    "📌 Aesthetica of a Rogue Hero - https://t.me/NeonFilesBot?start=Z2V0LTIxOTM0NDM0MDUzODczMDgtMjIwNjQ3NTc0NzM3NTQ0MQ",
    "📌 Attack On Titan - https://t.me/NeonFilesBot?start=Z2V0LTI4NDAwNDgwNjU1Njc3NTMtMjg2NzExNTIzNzM4OTI2MA",
    "📌 Attack On Titan Season 02 - https://t.me/NeonFilesBot?start=Z2V0LTI4NjgxMTc3MjUyMzQ1MDEtMjg4MjE1MjU1NTA2Nzg3NQ",
    "📌 Attack On Titan Season 03 - https://t.me/NeonFilesBot?start=Z2V0LTI4ODMxNTUwNDI5MTMxMTYtMjkwNzIxNDc1MTE5ODkwMA",
    "📌 Attack On Titan Season 04 - https://t.me/NeonFilesBot?start=Z2V0LTI5MDgyMTcyMzkwNDQxNDEtMjkzNzI4OTM4NjU1NjEzMA",
    "📌 Battle Game In 5 Seconds - https://t.me/NeonFilesBot?start=Z2V0LTIxMTgyNTY4MTY5OTQyMzMtMjEzMzI5NDEzNDY3Mjg0OA",
    "📌 Beast Tamer",
    "📌 Berserk of Gluttony",
    "📌 Black Summoner",
    "📌 Blue Lock",
    "📌 Blue Lock S2",
    "📌 BOFURI: I Don't get Hurt S01",
    "📌 BOFURI: I Don't get Hurt S02",
    "📌 Buddy Complex",
    "📌 Buddy Complex Specials",
    "📌 Buddy Daddies",
    "📌 Campfire Cooking in Another - https://t.me/NeonFilesBot?start=Z2V0LTMyOTgxODUwMTA4NDI4OS0zNDI4NTA4NDMwNzI0MjI",
    "📌 Cautious Hero - https://t.me/NeonFilesBot?start=Z2V0LTM0NDk1NjA2NzU0NzQyODEtMzQ2MzU5NTUwNTMwNzY1NQ",
    "📌 ChainSaw Man - https://t.me/NeonFilesBot?start=Z2V0LTQzMjA3MjI2MTI5ODg3MS00NDUxMDQ2MDMyODcwMDQ",
    "📌 Chained Soldier - https://t.me/NeonFilesBot?start=Z2V0LTMxNTU4MzE3MzY4MTg2NjgtMzE2OTg2NjU2NjY1MjA0Mg",
    "📌 Chaika Avenging Battle - https://t.me/NeonFilesBot?start=Z2V0LTI0NDAwNTU0MTUzMTY1OTQtMjQ1MjA4NTI2OTQ1OTQ4Ng",
    "📌 Chaika Coffin Princess - https://t.me/NeonFilesBot?start=Z2V0LTI0MjQwMTU2MDk3OTI3MzgtMjQzNzA0Nzk1MTc4MDg3MQ",
    "📌 Chivalry Of a Failed Knight - https://t.me/NeonFilesBot?start=Z2V0LTgzMDA1OTkzNTg1OTU0OC04NDMwOTIyNzc4NDc2ODE",
    "📌 Code:Breaker - https://t.me/NeonFilesBot?start=Z2V0LTMyMTY5ODM0OTUzNzgzNjktMzIzMjAyMDgxMzA1Njk4NA",
    "📌 Combatants Will Be Dispatched! - https://t.me/NeonFilesBot?start=Z2V0LTIxNzg0MDYwODc3MDg2OTMtMjE5MTQzODQyOTY5NjgyNg",
    "📌 Dandadan",
    "📌 Darling in the Franxx",
    "📌 Dawn of The Witch",
    "📌 Death March to the Parallel Wld",
    "📌 Dead Mount DeathPlay",
    "📌 Demon King Daimao",
    "📌 Demon King Daimao Specials",
    "📌 Demon Slayer S1 - https://t.me/NeonFilesBot?start=Z2V0LTEzNzY0MTU4MTE1MTU4OTMtMTQwMzQ4Mjk4MzMzNzQwMA",
    "📌 Demon Slayer Movie 01",
    "📌 Demon Slayer S2 Part 01",
    "📌 Demon Slayer S2 Part 02",
    "📌 Demon Slayer S3",
    "📌 Demon Slayer S4",
    "📌 Demon Sword Master of Excalibur",
    "📌 Failure Frame - https://t.me/NeonFilesBot?start=Z2V0LTIzODA5MDg2MzI0NDczNzUtMjM5Mzk0MDk3NDQzNTUwOA",
    "📌 Farming Life in another World - https://t.me/NeonFilesBot?start=Z2V0LTEwNjA2MzIxNDAyNjQ5NzgtMTA3MzY2NDQ4MjI1MzExMQ",
    "📌 Goblin Slayer S01",
    "📌 Goblin Slayer S02",
    "📌 Goblin Slayer: G.Crown (Movie)",
    "📌 Gods' Games we Play",
    "📌 Hell's Paradise - https://t.me/NeonFilesBot?start=Z2V0LTE3MjkyOTE1MzMwNDA3MjUtMTc0MzMyNjM2Mjg3NDA5OQ",
    "📌 How a Realist Hero Rebuilt - https://t.me/NeonFilesBot?start=Z2V0LTQ3NDE3Njc1MDc5ODk5My00ODgyMTE1ODA2MzIzNjc",
    "📌 How a Realist Hero Rebuilt S2 - https://t.me/NeonFilesBot?start=Z2V0LTQ4OTIxNDA2ODQ3NzYwOC01MDMyNDg4OTgzMTA5ODI",
    "📌 How not to Summon a Demon - https://t.me/NeonFilesBot?start=Z2V0LTQxODAzNzQzMTQ2NTQ5Ny00MzEwNjk3NzM0NTM2MzA",
    "📌 Hundred - https://t.me/NeonFilesBot?start=Z2V0LTIxMzUyOTkxMTAzNjMzMzAtMjE0ODMzMTQ1MjM1MTQ2Mw",
    "📌 I Got a Cheat Skill in Another",
    "📌 I Parry Everything",
    "📌 I Shall survive using potions",
    "📌 I've been killing Slimes for 300",
    "📌 I'm Quitting Heroing",
    "📌 In another world with my S01",
    "📌 In another world with my S02",
    "📌 Infinite Dendrogram",
    "📌 Isekai Cheat Magician",
    "📌 Jujutsu Kaisen",
    "📌 Kaiju No 8 - https://t.me/NeonFilesBot?start=Z2V0LTEyOTgyMjE3NTk1ODcwOTUtMTMxMTI1NDEwMTU3NTIyOA",
    "📌 Knight's & Magic - https://t.me/NeonFilesBot?start=Z2V0LTI0NTgxMDAxOTY1MzA5MzItMjQ3NDE0MDAwMjA1NDc4OA",
    "📌 Konosuba! An Explosion - https://t.me/NeonFilesBot?start=Z2V0LTE1MzY4MTM4NjY3NTQ0NTMtMTU0OTg0NjIwODc0MjU4Ng",
    "📌 Konosuba Movie - https://t.me/NeonFilesBot?start=Z2V0LTE1MzE4MDE0Mjc1MjgyNDgtMTUzNDgwODg5MTA2Mzk3MQ",
    "📌 Konosuba Season 01 - https://t.me/NeonFilesBot?start=Z2V0LTE0OTQ3MDkzNzcyNTQzMzEtMTUwNTczNjc0MzU1MTk4Mg",
    "📌 Konosuba Season 02 - https://t.me/NeonFilesBot?start=Z2V0LTE1MDY3MzkyMzEzOTcyMjMtMTUxNzc2NjU5NzY5NDg3NA",
    "📌 Konosuba Season 03 - https://t.me/NeonFilesBot?start=Z2V0LTE1MTg3NjkwODU1NDAxMTUtMTUzMDc5ODkzOTY4MzAwNw",
    "📌 Log Horizon",
    "📌 Log Horizon Season 02",
    "📌 Log Horizon Season 03",
    "📌 Lookism",
    "📌 Mashle: Magic And Muscles - https://t.me/NeonFilesBot?start=Z2V0LTIzNTA4MzM5OTcwOTAxNDUtMjM2Mzg2NjMzOTA3ODI3OA",
    "📌 Mashle: Magic And Muscles S02 - https://t.me/NeonFilesBot?start=Z2V0LTIzNjU4NzEzMTQ3Njg3NjAtMjM3ODkwMzY1Njc1Njg5Mw",
    "📌 My Dress-Up Darling - https://t.me/NeonFilesBot?start=Z2V0LTI3OTU5Mzg2MDAzNzcxNDktMjgwOTk3MzQzMDIxMDUyMw",
    "📌 My Isekai life - https://t.me/NeonFilesBot?start=Z2V0LTczMTgxNjEyNzAyNTkzMC03NDQ4NDg0NjkwMTQwNjM",
    "📌 My Instant Death Ability - https://t.me/NeonFilesBot?start=Z2V0LTE1NTA4NDg2OTY1ODc4MjctMTU2NDg4MzUyNjQyMTIwMQ",
    "📌 Myriad Colors Phantom World - https://t.me/NeonFilesBot?start=Z2V0LTI5OTY0MzYxNjk0MjUzNDktMzAxMTQ3MzQ4NzEwMzk2NA",
    "📌 Myriad Colors Phantom Specials - https://t.me/NeonFilesBot?start=Z2V0LTMwMTI0NzU5NzQ5NDkyMDUtMzAyMjUwMDg1MzQwMTYxNQ",
    "📌 My Unique Skill Makes Me OP - https://t.me/NeonFilesBot?start=Z2V0LTE2MTYwMTA0MDY1Mjg0OTItMTYyOTA0Mjc0ODUxNjYyNQ",
    "📌 Ningen Fushin",
    "📌 Noblesse",
    "📌 One Punch Man",
    "📌 One Punch Man S2",
    "📌 Overflow Uncensored",
    "📌 OverLord",
    "📌 Our Last Crusade",
    "📌 Parallel World Pharmacy",
    "📌 Rage Of Bahamut - https://t.me/NeonFilesBot?start=Z2V0LTMxODY5MDg4NjAwMjExMzktMzIwMDk0MzY4OTg1NDUxMw",
    "📌 Re Monster - https://t.me/NeonFilesBot?start=Z2V0LTg3MjE2NDQyNTM1OTY3MC04ODUxOTY3NjczNDc4MDM",
    "📌 Record of Grancrest War - https://t.me/NeonFilesBot?start=Z2V0LTIxNTAzMzY0MjgwNDE5NDUtMjE3",
    "📌 Re Reborn as a Vending Machine - https://t.me/NeonFilesBot?start=Z2V0LTI1MjYyNjkzNzAwMDczMjAtMjU0MDMwNDE5OTg0MDY5NA",
    "📌 Redo of Healer - https://t.me/NeonFilesBot?start=Z2V0LTEwMDI0ODc4NDUyNDEwMDAtMTAxNTUyMDE4NzIyOTEzMw",
    "📌 Reincarnated as a Sword - https://t.me/NeonFilesBot?start=Z2V0LTg0NDA5NDc2NTY5MjkyMi04NTcxMjcxMDc2ODEwNTU",
    "📌 Reincarnated as Slime S01 - https://t.me/NeonFilesBot?start=Z2V0LTU5MTQ2NzgyODY5MjE5MC02MTY1MzAwMjQ4MjMyMTU",
    "📌 Reincarnated as Slime S02 - https://t.me/NeonFilesBot?start=Z2V0LTYxNzUzMjUxMjY2ODQ1Ni02NDM1OTcxOTY2NDQ3MjI",
    "📌 Reincarnated as Slime S03 - https://t.me/NeonFilesBot?start=Z2V0LTY0NDU5OTY4NDQ4OTk2My02NzE2NjY4NTYzMTE0NzA",
    "📌 Reincarnated as Slime Movie - https://t.me/NeonFilesBot?start=Z2V0LTY3MjY2OTM0NDE1NjcxMS02NzQ2NzQzMTk4NDcxOTM",
    "📌 Reincarnatn of Strongest Exorcist - https://t.me/NeonFilesBot?start=Z2V0LTE0MjM1MzI3NDAyNDIyMi0xNTYzODgxMDM4NTc1OTY",
    "📌 Rent-A-Girlfriend - https://t.me/NeonFilesBot?start=Z2V0LTMyNjAwOTA0NzI3MjM3MzItMzI3NDEyNTMwMjU1NzEwNg",
    "📌 Rent-A-Girlfriend Season 02 - https://t.me/NeonFilesBot?start=Z2V0LTMyNzUxMjc3OTA0MDIzNDctMzI4OTE2MjYyMDIzNTcyMQ",
    "📌 Rent-A-Girlfriend Season 03 - https://t.me/NeonFilesBot?start=Z2V0LTMyOTAxNjUxMDgwODA5NjItMzMwNDE5OTkzNzkxNDMzNg",
    "📌 Restaurant to Another World S1 - https://t.me/NeonFilesBot?start=Z2V0LTI5NjUzNTkwNDYyMjI4NzgtMjk3OTM5Mzg3NjA1NjI1Mg",
    "📌 Restaurant To Another World S2 - https://t.me/NeonFilesBot?start=Z2V0LTMzMjAyMzk3NDM0MzgxOTItMzMzNDI3NDU3MzI3MTU2Ng",
    "📌 Rokka - https://t.me/NeonFilesBot?start=Z2V0LTEyNjkxNDk2MTIwNzUxMDYtMTI4MjE4MTk1NDA2MzIzOQ",
    "📌 Shangri-La Frontier",
    "📌 Seirei Gensouki Spirit Chronicles",
    "📌 Skeleton Knight in another World",
    "📌 Sky Wizards Academy",
    "📌 Solo Leveling",
    "📌 Spy X Family",
    "📌 Spy X Family Season 02",
    "📌 Spy X Family : Code White",
    "📌 Suppose a Kid from the Last",
    "📌 Sword Art Online S1",
    "📌 Sword Art Online S2",
    "📌 Sword Art Online S3",
    "📌 Sword Art Online S4",
    "📌 Sword Art Online: Gun Gale",
    "📌 Sword Art Online Movies",
    "📌 Sweet Reincarnation",
    "📌 The Daily Life of the Immortal S1 - https://t.me/NeonFilesBot?start=Z2V0LTExODI5MzU2NTczODQzODAtMTE5ODk3NTQ2MjkwODIzNg",
    "📌 The Daily Life of the Immortal S2 - https://t.me/NeonFilesBot?start=Z2V0LTExOTk5Nzc5NTA3NTM0NzctMTIxMzAxMDI5Mjc0MTYxMA",
    "📌 The Daily Life of the Immortal S3 - https://t.me/NeonFilesBot?start=Z2V0LTEyMTQwMTI3ODA1ODY4NTEtMTIyNzA0NTEyMjU3NDk4NA",
    "📌 The Daily Life of the Immortal S4 - https://t.me/NeonFilesBot?start=Z2V0LTEyMjgwNDc2MTA0MjAyMjUtMTI0MTA3OTk1MjQwODM1OA",
    "📌 The Dreaming Boy is a Realist",
    "📌 The Eminence in Shadow S1 - https://t.me/NeonFilesBot?start=Z2V0LTExMTg3NzY0MzUyODg5NTYtMTEzOTgyODY4MDAzOTAxNw",
    "📌 The Eminence in Shadow S2 - https://t.me/NeonFilesBot?start=Z2V0LTExNDA4MzExNjc4ODQyNTgtMTE1Mzg2MzUwOTg3MjM5MQ",
    "📌 The Executioner and Her Way of",
    "📌 The Foolish Angel Dances with",
    "📌 The God of HighSchool",
    "📌 The Greatest Alchemist",
    "📌 The Greatest Demon lord Reborn - https://t.me/NeonFilesBot?start=Z2V0LTEwNDY1OTczMTA0MzE2MDQtMTA1OTYyOTY1MjQxOTczNw",
    "📌 The Hidden dungeon only I",
    "📌 The IceBlade Sorcerer - https://t.me/NeonFilesBot?start=Z2V0LTcxNzc4MTI5NzE5MjU1Ni03MzA4MTM2MzkxODA2ODk",
    "📌 The Misfit of Demon King",
    "📌 The Misfit of Demon King S02",
    "📌 The Ossan Newbie Adventurer",
    "📌 The Rising of the Shield Hero S1 - https://t.me/NeonFilesBot?start=Z2V0LTUzNTMyODUwOTM1ODY5NC01NjEzOTMxOTMzMzQ5NjA",
    "📌 The Rising of the Shield Hero S2 - https://t.me/NeonFilesBot?start=Z2V0LTU2MjM5NTY4MTE4MDIwMS01NzY0MzA1MTEwMTM1NzU",
    "📌 The Rising of the Shield Hero S3 - https://t.me/NeonFilesBot?start=Z2V0LTU3NzQzMjk5ODg1ODgxNi01OTA0NjUzNDA4NDY5NDk",
    "📌 The Slime Diaries - https://t.me/NeonFilesBot?start=Z2V0LTY3NTY3NjgwNzY5MjQzNC02ODg3MDkxNDk2ODA1Njc",
    "📌 The Strongest Sage with weakst - https://t.me/NeonFilesBot?start=Z2V0LTEwMTY1MjI2NzUwNzQzNzQtMTAyOTU1NTAxNzA2MjUwNw",
    "📌 The Testament of Sister",
    "📌 The Testament of Sister S02",
    "📌 The Testament of Sister Special",
    "📌 The Weakest Tamer Began",
    "📌 Tomo-Chan is a Girl!",
    "📌 Toradora!",
    "📌 Toradora! Specials",
    "📌 Tower Of God",
    "📌 Tower Of God Season 02",
    "📌 Transformers Prime S1",
    "📌 Transformers Prime S2",
    "📌 Transformers Prime S3",
    "📌 Transformers Prime Movie",
    "📌 TsukiMichi Moonlit Fantasy S1 - https://t.me/NeonFilesBot?start=Z2V0LTkzMTMxMTIwODIyODg4OS05NDQzNDM1NTAyMTcwMjI",
    "📌 TsukiMichi Moonlit Fantasy S2",
    "📌 UQ Holder! - https://t.me/NeonFilesBot?start=Z2V0LTE5NjQ4NzYxNzY2NzIzNjAtMTk4NTkyODQyMTQyMjQyMQ",
    "📌 Unwanted undead Adventurer",
    "📌 Vermeil in Gold - https://t.me/NeonFilesBot?start=Z2V0LTMxNDA3OTQ0MTkxNDAwNTMtMzE1NDgyOTI0ODk3MzQyNw",
    "📌 Violet Evergarden - https://t.me/NeonFilesBot?start=Z2V0LTIzMTI3Mzk0NTg5NzA5ODctMjM0NDgxOTA3MDAxODY5",
    "📌 Wind Breaker",
    "📌 Wistoria : wand and sword",
    "📌 Wrong way to use Healing Magic"
    ]
    

# MyselfNeon
# Don't Remove Credit 🥺
# Telegram Channel @NeonFiles
