class script(object):
    # Plain text with names and URLs
    NEON_TXT = [
    "📌 A Returner's Magic be Special",
    "📌 Akashic Records of Magical",
    "📌 An Archdemons Dilemma",
    "📌 Banished from Hero's Party S1",
    "📌 Banished from Hero's Party S2",
    "📌 Black Summoner",
    "📌 Beast Tamer",
    "📌 Chillin' in Another World lvl 2",
    "📌 Demon Sword Master of Excalibur",
    "📌 Farming Life in another World",
    "📌 I'm Quitting Heroing",
    "📌 Isekai Cheat Magician",
    "📌 Kaiju No 8",
    "📌 Lookism",
    "📌 My Isekai life",
    "📌 Our Last Crusade",
    "📌 Re Monster",
    "📌 Redo of Healer",
    "📌 Reincarnated as a Sword",
    "📌 Reincarnatn of Strongest Exorcist",
    "📌 Rokka",
    "📌 Reincarnated as Slime S01",
    "📌 Reincarnated as Slime S02",
    "📌 Reincarnated as Slime Movie",
    "📌 Skeleton Knight in another World",
    "📌 Solo Leveling",
    "📌 The Daily Life of the Immortal S1",
    "📌 The Daily Life of the Immortal S2",
    "📌 The Daily Life of the Immortal S3",
    "📌 The Daily Life of the Immortal S4",
    "📌 The Eminence in Shadow S1",
    "📌 The Eminence in Shadow S2",
    "📌 The Greatest Demon lord Reborn",
    "📌 The Slime Diaries",
    "📌 The Strongest Sage with weakst",
    "📌 TsukiMichi Moonlit Fantasy S1",
    "📌 Wind Breaker",
    "📌 Wrong way to use Healing Magic"
    ]
  
